#!/usr/bin/env python3

import socket
import select

HOST = '<broadcast>'
PORT = 6987

LHOST = ''
LPORT = 6988

data = b'1'

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.bind ((LHOST,LPORT))
sock.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, 1)
sock.sendto(data, (HOST,PORT))
print ("Request sent to broadcast address...")

ready = select.select([sock],[],[],5)
if ready[0]:
	rbytes, addr = sock.recvfrom(64)
	print ("Raspberry Pi is @ " + str(addr[0]))
else:
	print ("Request timed out")
sock.close()
